# Generated by Django 4.1.5 on 2023-01-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_date_time', models.DateTimeField(auto_created=True)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_request', models.TextField(help_text='Enter your request here', verbose_name='How can I help you?')),
                ('chatgpt_response', models.TextField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('prompt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat Prompts',
            },
        ),
    ]
