# Generated by Django 4.1.5 on 2023-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatGPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprompts',
            options={'verbose_name_plural': 'User Chat Prompts'},
        ),
        migrations.AlterField(
            model_name='userprompts',
            name='prompt_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
